apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: service-ingress
spec:
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 3
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: status-port
            port: 15021 
            targetPort: 15021
          - name: http2
            port: 80 
            targetPort: 8080
        type: ClusterIP
        serviceAnnotations:
          cloud.google.com/neg: '{"ingress": true}'
          cloud.google.com/backend-config: '{"default":"ingress"}'
          cloud.google.com/app-protocols: '{"http2":"HTTP"}'
  components:
    ingressGateways:
      - name: istio-ilbgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
          serviceAnnotations:
            cloud.google.com/load-balancer-type: "Internal"
            networking.gke.io/internal-load-balancer-allow-global-access: "true"
      - name: istio-ingressgateway
        enabled: true